apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: acrbtris01.azurecr.io/webapi:<build_id>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-key